### PR TITLE
remove space from comma delimited strings of ints

### PR DESCRIPTION
**Pull request by 0xor1**
this causes issues trying to parse ints back from the string

### CODE REVIEW

**Comment by arp242** [comment]
Note this is not necessarily a compatible change, and may also look ugly when used in user-facing areas. Also, JoinFloat() uses a space as well, so now it's inconsistent, and I'm pretty sure this will break tests?

**Comment by arp242** [comment]
What are you trying to do btw? `sqlutil.IntList` may already cover your use case.

**Comment by ripexz** [comment]
Yeah defo breaking change, don't see JoinFloat though? 🤔 I guess the assumption here is that this would be inverse of `CSVtoInt64Slice`, so maybe add a new method that's `Int64SliceToCSV`? 😅

**Comment by arp242** [comment]
Oh, sorry; I just have JoinFloat() locally 😅

There is already a `strings.TrimSpace()` in `CSVtoInt64Slice()`, so that *should* work equally well for `1,2` and `1, 2`.

**Comment by arp242** [comment]
As for Travis, that actually broke for a lot of repos around the time I left Teamwork, so I think that's probably not a coincidence. Probably something linked to my accounts that no longer has access?

**Comment by ripexz** [comment]
> There is already a `strings.TrimSpace()` in `CSVtoInt64Slice()`, so that _should_ work equally well for `1,2` and `1, 2`.

so then

> this causes issues trying to parse ints back from the string

might not be correct and this PR is unnecessary? 😅 

> As for Travis, that actually broke for a lot of repos around the time I left Teamwork, so I think that's probably not a coincidence. Probably something linked to my accounts that no longer has access?

I know there were issues with codecov but travis should be OK, will look into it though 🤔

**Pull request closed without merging**
